### ISSUE TITLE
block

### ISSUE THREAD

**Issue by pando85** [pando85/rash#14]
Add block structure to allow create tasks in yaml with common fields (when, ignore_errors, loop, changed_when, until).
This create tasks included in block with that fields:

Example:
```yaml
- name: Skip all if not envar NOT_SKIP
  when: env.NOT_SKIP is defined 
  block:
    - name: Say hello
      command: echo hi

    - command: echo bye
```

Expands to:
```yaml
- name: Say hello
  command: echo hi
  when: env.NOT_SKIP is defined

- command: echo bye
  when: env.NOT_SKIP is defined
```
