### ISSUE TITLE
module copy

### ISSUE THREAD

**Issue by pando85** [pando85/rash#3]
```yaml
params:
  content: String
  dest: String
  mode:
    type: String
    default: 0644
    description: 4 numbers for octal mode representation or 3 assuming omitted is zero. 
output: dest
```
