### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by pando85** [pando85/rash#34]
Optional field for task that allow inject environment variables.

**Comment by pando85** [comment]
Example:

```yaml
- command: "echo $FOO"
  environment:
    FOO: yea
```
