### ISSUE TITLE
pause

### ISSUE THREAD

**Issue by pando85** [pando85/rash#37]
Pause execution amount of time fixed or until approval.  

```yaml
params:
  minutes:
    type: String
    description: A positive number of minutes to pause for. 
  seconds: String
  prompt:
    type: String
    description:  Optional text to use for the prompt message.
output: "Press enter to continue, Ctrl+C to interrupt" or "{{ prompt }} if exists"
```
