### ISSUE TITLE
wait_for

### ISSUE THREAD

**Issue by pando85** [pando85/rash#38]
Wait until something passed or `timeout` reached.  This fails except `ignore_errors` set to `true`.

```yaml
params:
  connect_timeout:
    default: 5
    type: Int
    description: Maximum number of seconds to wait for a connection to happen before closing and retrying. 
  port:
    type: Int
    description: Port number to poll.
  timeout:
    type: Int
    description:  Maximum number of seconds to wait for.
  
output: "{{ port }}"
```
