### ISSUE TITLE
module template

### ISSUE THREAD

**Issue by pando85** [pando85/rash#4]
As copy but with jinja2 rendering from src file.
This will need all facts as input.

```yaml
params:
  src: String
  dest: String
  mode:
    type: String
    default: 0644
    description: 4 numbers for octal mode representation or 3 assuming omitted is zero. 
output: dest
```
