### ISSUE TITLE
builtins

### ISSUE THREAD

**Issue by pando85** [pando85/rash#6]
Create facts `rash` builtins.

This must contain all args easily accessible inside `rash` key at the same level that `env` facts:
```yaml
rash:
  args:
    - all
    - arguments
    - passed
    - to
    - rash
    - after
    - --
    - as
    - string
  user: current user
  dir: current `.rh` absolute path
```
