### ISSUE TITLE
command args as list

### ISSUE THREAD

**Issue by pando85** [pando85/rash#60]
```yaml
command:
  argv:
    - ls
    - -alrth
    - /
```

If not list passed execute as `/bin/sh -c {string_arg}`.
